name: 'Debug workflow'
on: [push]

jobs:
  build:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          node-version: 12.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Dnn Version
        id: dnnVersion
        uses: valadas/dnn-platform-get-version@develop
      - run: eche the Dnn version is {{ toJson(steps.dnnVersion.outputs.version }}
      - name: Hello World
        uses: valadas/gh-action-template@develop
        id: greet
        with:
          who-to-greet: Language Packs
      - run: echo The greeting is ${{ steps.greet.outputs.greeting }}
      - run: npm install
      - run: npm run build
      - uses: ./.github/actions/debug-action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        id: debug
      - run: echo There was an amazing message - ${{ steps.debug.outputs.amazing-message }}
