name: 'Debug workflow'
on: [push]

jobs:
  build:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Dnn Version
        id: dnnVersion
        uses: valadas/dnn-platform-get-version@develop
      - run: echo the Dnn version is ${{ toJson(steps.dnnVersion.outputs.version) }}
      - run: echo the manifestSaveVersionString is ${{ toJson(steps.dnnVersion.outputs.version).manifestSafeVersionString }}
      - run: npm install
      - run: npm run build
      - uses: ./.github/actions/debug-action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.dnnVersion.outputs.version.manifestSafeVersionString }}
        id: debug
      - run: echo There was an amazing message - ${{ steps.debug.outputs.amazing-message }}
