name: 'Debug workflow'
on: [push]

jobs:
  build:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Hello World
        uses: valadas/gh-action-template@develop
        id: ghTemplate
        with:
          who-to-greet: Language Pack
      - run: echo The greeting is ${{ steps.ghTemplate.greeting }}
      - run: npm install
      - run: npm run build
      - uses: ./.github/actions/debug-action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        id: debug
      - run: echo There was an amazing message - ${{ steps.debug.outputs.amazing-message }}
